# Auto-Load CSV Data for Trade Analyzer
# This script reads all CSV files from the trace/TradeAnalyzer folder
# and generates a JavaScript file that the app loads automatically

$csvFolder = "C:\Users\prueba\Documents\NinjaTrader 8\trace\TradeAnalyzer"
$outputFile = "C:\Users\prueba\Documents\NinjaTrader 8\bin\Custom\Strategies\TradeAnalyzer\auto_data.js"

Write-Host "=== Trade Analyzer Auto-Load ===" -ForegroundColor Cyan
Write-Host "Reading CSVs from: $csvFolder"

# Get all CSV files
$csvFiles = Get-ChildItem -Path $csvFolder -Filter "*.csv" -ErrorAction SilentlyContinue

if ($csvFiles.Count -eq 0) {
    Write-Host "No CSV files found!" -ForegroundColor Yellow
    exit
}

Write-Host "Found $($csvFiles.Count) CSV files" -ForegroundColor Green

$allTrades = @()

foreach ($file in $csvFiles) {
    Write-Host "  Processing: $($file.Name)" -ForegroundColor Gray
    
    # Read CSV content
    $content = Get-Content -Path $file.FullName -Encoding UTF8
    
    # Skip header (first line) and process data
    for ($i = 1; $i -lt $content.Count; $i++) {
        $line = $content[$i].Trim()
        if ([string]::IsNullOrEmpty($line)) { continue }
        
        $cols = $line -split ","
        
        # Need at least 9 columns for valid trade
        if ($cols.Count -lt 9) { continue }
        
        # Build trade object (matching CSV format)
        $trade = @{
            id = $cols[0]
            instrument = $cols[1]
            entryTime = $cols[2]
            type = $cols[3]
            entryPrice = $cols[4]
            exitTime = if ($cols[5]) { $cols[5] } else { "" }
            exitPrice = $cols[6]
            result = $cols[7]
            pnl = $cols[8]
            mae = if ($cols.Count -gt 9) { $cols[9] } else { "0" }
            mfe = if ($cols.Count -gt 10) { $cols[10] } else { "0" }
            setup = if ($cols.Count -gt 11) { $cols[11] } else { "" }
            attempt = if ($cols.Count -gt 12) { $cols[12] } else { "1" }
            riskReward = if ($cols.Count -gt 13) { $cols[13] } else { "0" }
        }
        
        $allTrades += $trade
    }
}

Write-Host "Total trades loaded: $($allTrades.Count)" -ForegroundColor Green

# Generate JavaScript file
$jsContent = "// Auto-generated by load_data.ps1 - $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')`n"
$jsContent += "// DO NOT EDIT - This file is regenerated each time you run the script`n"
$jsContent += "window.AUTO_CSV_DATA = [`n"

foreach ($trade in $allTrades) {
    $jsContent += "  {`n"
    $jsContent += "    id: `"$($trade.id)`",`n"
    $jsContent += "    instrument: `"$($trade.instrument)`",`n"
    $jsContent += "    entryTime: `"$($trade.entryTime)`",`n"
    $jsContent += "    type: `"$($trade.type)`",`n"
    $jsContent += "    entryPrice: $($trade.entryPrice),`n"
    $jsContent += "    exitTime: `"$($trade.exitTime)`",`n"
    $jsContent += "    exitPrice: $($trade.exitPrice),`n"
    $jsContent += "    result: `"$($trade.result)`",`n"
    $jsContent += "    pnl: $($trade.pnl),`n"
    $jsContent += "    mae: $($trade.mae),`n"
    $jsContent += "    mfe: $($trade.mfe),`n"
    $jsContent += "    setup: `"$($trade.setup)`",`n"
    $jsContent += "    attempt: $($trade.attempt),`n"
    $jsContent += "    riskReward: $($trade.riskReward)`n"
    $jsContent += "  },`n"
}

$jsContent += "];`n"

# Write to file
$jsContent | Out-File -FilePath $outputFile -Encoding UTF8

Write-Host ""
Write-Host "SUCCESS! Generated: $outputFile" -ForegroundColor Green
Write-Host "Now open index.html in your browser" -ForegroundColor Cyan
Write-Host ""
